[package]
name = "tp-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "TexturePacker-RS command-line interface"

[dependencies]
tp-core = { path = "../tp-core", features = ["gpu-formats"] }
serde_json.workspace = true

[lints]
workspace = true

[dev-dependencies]
image.workspace = true
